initialise react app
ccobasi/book-store pull request #1
Opened 2021-08-30 22:46 UTC by ccobasi

- Setup react and redux.
- Structure application using feature folder
- Add React Router 
- Display books and categories

2021-08-30 22:59 UTC, dasileker requested changes
### **Hi @ccobasi** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **To Highlight**
- The PR is good.
- The commit are good. 
- The Linters are passing.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-30 22:59 UTC, dasileker commented on src/redux/books/books.js
> +                <div className="row">
- [ ] The **`book.js`** should be a **`propTypes`** for the **Title** and **Author** see the screenshot 👇

![hfhf](https://user-images.githubusercontent.com/61562626/131416151-c4a1c5da-49cf-48ed-be5b-15650a4ad899.jpeg)

2021-08-30 22:59 UTC, dasileker commented on src/redux/categories/categories.js
> +            <div className="card-body">
- [ ] Also the same should be for the **category**

2021-08-31 15:42 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-31 15:43 UTC, mikenath223 commented on src/redux/books/books.js
> +  return (
- [ ] OPTIONAL - Kindly place the Book component in the components folder. The redux folder should only contain reducers and the redux store.

2021-08-31 15:44 UTC, mikenath223 commented on src/redux/categories/categories.js
> +    <div className="main-container">
- [ ] Also for the Category kindly place it in the components folder.

2021-09-06 14:15 UTC, merged